# 1D arrays in NumPy

In [ ]:
import numpy as np

The basic function for creating an array is the array() function, that is a function of numpy so it can be accessed via np.array(). It takes a sequence and makes an array out of it.
* convert the type: array.astype('type')
* round the decimals: array = np.around(array, decimals = n) or np.around(array, decimals = n, out = outputArray)

---

### What is an array?
Arrays are row vectors with FIXED LENGTH. Also, they are homogeneous, meaning that ALL THE ELEMENTS HAVE THE SAME TYPE.

---

Printed lists have numbers separated by commas, while arrays have no separator between elements.

To measure the length of a list, use len(), but for an array you should use the size attribute of arrays, so NameArray.size.

Another attribute is array.dtype: this returns the type of the elements of the array, inferred by the elements themselves, and the bits size (ex 64, 32, 16...). You can also use the core function type() to check. You can convert between types (for instance, fro integer to float of given precision) by exploting the attribute dtype directly inside the definition of the array you're making. Pass it as an argument after the list of numbers to put inside the array, and don't forget that the attribute is part of numpy too.



In [ ]:
arr = np.array([1,1,1,1], dtype = np.float64)
arr

array([1., 1., 1., 1.])

To make sequences of zeros or ones, you should use the pre-defined functions np.zeros(number) or np.ones(number). For other numbers, think of concatenation of lists and exploit that feature: for ex., [5]*2 will give you [5, 5] as the sequence to pass inside the array.

Another thing you can do is to create sequences from a range of values: the function np.arange() is the specular function of range, but it produces an array.

In [ ]:
arr1 = np.array([0]*10, dtype=np.float32)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [ ]:
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Sequences of customary spacing

Remember: arange() can take in floats as well (range could only handle integers). This may lead to disasters with endpoints considered one time and not the other. To produce an array that is storing a sequence of linearly spaced points, you should use np.linspace(start, end, number of points). There is a version of logarithmic sequences too, that takes as starting and ending points the powers of 10 (default behaviour), np.logspace(initial power, final power, number of points).

In [ ]:
arr2 = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr3 = np.arange(5,10)
arr

array([5, 6, 7, 8, 9])

In [ ]:
arr4 = np.arange(5,15,2)
arr

array([ 5,  7,  9, 11, 13])

In [ ]:
arr5 = np.linspace(0,1,11)
arr5

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
np.logspace(-10,-5,num=6,endpoint=True,base=10.0)

array([1.e-10, 1.e-09, 1.e-08, 1.e-07, 1.e-06, 1.e-05])

## 1.2 Indexing and slicing
This is fun, trust me.

Indexing is the same as lists, so with square brackets. You can access more than one element with a colon [start:end].

Slicing with lists makes another list that is a copy.
**SLICING ARRAYS ONLY TAKES A PORTION OF THE ORIGINAL ARRAY WITHOUT MAKING A COPY -> operations made on the copy affect the original array.**

To make a copy of an array, use np.copy.

**Broadcasting**: substituting a given number of elements in a list by a single operation was not possible (meaning that you couldn't take a list of 2 elements, put it equal to 1 elements and obtain a list made of 2 equal entries that are the second element. Here you can, by using indexing and selecting the elements that you want to substitute. To select all the elements, use array[:].

In [ ]:
arr

array([ 5,  7,  9, 11, 13])

In [ ]:
slicy = arr[2:4]
slicy

array([ 9, 11])

In [ ]:
slicy[:]=0
slicy

array([0, 0])

In [ ]:
arr

array([ 5,  7,  0,  0, 13])

## 1.3 Vectorization (or arithmetical operations)

Vectorization si a property of arrays, meaning that they act as they were methematical vectors. So operations are made *elementwise*: summing two arrays (OF SAME LENGTH ONLY) gives an array of same length withthe sum of the corresponding entries as elements. Same goes for multiplication by a scalar number.

To compute the sum of all the elements in an array, use np.sum(). To compute a scalar product of x and y, for example, use np.sum(x*y). To compute the product of all the elements use np.prod().

NumPy contains a lot of the functions present in the Math library also, but designed to make operations on an entire array and return an array also. They are much faster than their math counterpart. Examples are np.sqrt(), np.log(), np.sin() and so on.

Other useful functions:
* np.amin() returns the element with the minimum value
* np.argmax() returns the index of the element with max value
* np.sort
* np.isfinite()

# 2 Two-dimensional arrays

## 2.1 Creating

To create a matrix, one should use a "list of lists", so an object whose elements are lists. An array of a list of lists is a matrix.

The dimension of a matrix is 2, you can retrieve that by exploiting the attribute ndim of the matrix, matrix.ndim. dtype methods apply to matrices too. The attribute shape, matrix.shape, instead, gives you the n x m dimension of the matrix as a tuple. You can reverse this property and make matrixes of zeros and ones by passing a tuble with wanted shape as the argument.
* matrix of zeros: np.zeros((n,m))
* matrix of ones: np.ones((n,m))
* identity of dim n: np.identity(n)
* vector -> matrix: array.reshape((n,m))
* columns -> matrix: np.column_stack((array1,array2))
* convert the type: array.astype('type')
* round the decimals: array = np.around(array, decimals = n) or np.around(array, decimals = n, out = outputArray)

In [ ]:
A = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
A

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [ ]:
Matri = np.array(A)
Matri

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
A = np.arange(0,10).reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 2.2 Indexing, slicing

Indexing is very simple, just call the name of the matrix and the positions (REMEMBER ALWAYS PYTHON STARTS FROM 0) in square brackets, separated by a comma. 

In [ ]:
A = np.arange(0,9).reshape(3,3)
print(A, A[1,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]] 4


Slicing is very easy. Just slice the row first with a couple start:end and the column then.

In [ ]:
A[1,:]

array([3, 4, 5])

Bradcasting is the same as for arrays/vectors. Remember that what you do on a slice of the original matrix affects the original matrix as well.

## 2.3 Vectorization

Arithmetical operations are done elementwise (element by element between the corresponding ones). Sum of two matrixes is fine.

* matrix multiplication: np.dot(matrix1, matrix2), @ (Python 3.5 and above) (applies to 1D arrays too)
* transposed matrix: np.transpose(matrix)
* trace of a matrix: np.trace(matrix)

In [ ]:
# Printing a matrix row by row
for row in A:
  print(row)

[0 1 2]
[3 4 5]
[6 7 8]


# 3 File input and output

NumPy contains functions that allow you to traslate the content of a file directly as an array.
* making array from data file: np.loadtxt("nameFile", skiprows = n, skipcolumns = m)
* store each column in a separate array: use loadtxt option unpack = True and put it all equal to 2 arrays

A more powerful function is np.genfromtxt.

* saving: np.savetxt("NameFile", (array1, array2,...))

In [ ]:
%%writefile dataset.txt
x y
0 1
1 1.2
2 1.1
3 0.9

Overwriting dataset.txt


In [ ]:
x, y = np.loadtxt("dataset.txt", skiprows = 1, unpack = True)
print (x, y)

[0. 1. 2. 3.] [1.  1.2 1.1 0.9]
